###
#
# Category Table
#
###

CREATE TABLE CATEGORY(
  ID CHAR(36) NOT NULL,
  DISPLAY_NAME VARCHAR(100) NOT NULL,
  PATH VARCHAR(125) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE CATEGORY
  ADD UNIQUE INDEX `IX_CAT_DISPLAY_NAME` (DISPLAY_NAME);

ALTER TABLE CATEGORY
  ADD UNIQUE INDEX `IX_CAT_PATH` (PATH);

###
#
# Safety Deposit Box Table
#
###

CREATE TABLE SAFE_DEPOSIT_BOX(
  ID CHAR(36) NOT NULL,
  CATEGORY_ID CHAR(36) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  PATH VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE SAFE_DEPOSIT_BOX
  ADD UNIQUE INDEX `IX_SDBOX_NAME` (NAME);

ALTER TABLE SAFE_DEPOSIT_BOX
  ADD UNIQUE INDEX `IX_SDBOX_PATH` (PATH);

ALTER TABLE SAFE_DEPOSIT_BOX
  ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);

###
#
# Role Table
#
###

CREATE TABLE ROLE(
  ID CHAR(36) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE ROLE
    ADD UNIQUE INDEX `IX_ROLE_NAME` (NAME);

###
#
# User Group Table
#
###

CREATE TABLE USER_GROUP(
  ID CHAR(36) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE USER_GROUP
  ADD UNIQUE INDEX `IX_USER_GRP_NAME` (NAME);

###
#
# User Group Permissions Join Table
#
###

CREATE TABLE USER_GROUP_PERMISSIONS(
  ID CHAR(36) NOT NULL,
  USER_GROUP_ID CHAR(36) NOT NULL,
  ROLE_ID CHAR(36) NOT NULL,
  SDBOX_ID CHAR(36) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE USER_GROUP_PERMISSIONS
  ADD UNIQUE INDEX `IX_USER_GROUP_TO_SDBOX` (USER_GROUP_ID, SDBOX_ID);

ALTER TABLE USER_GROUP_PERMISSIONS
  ADD FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP(ID);

ALTER TABLE USER_GROUP_PERMISSIONS
  ADD FOREIGN KEY (SDBOX_ID) REFERENCES SAFE_DEPOSIT_BOX(ID);

ALTER TABLE USER_GROUP_PERMISSIONS
  ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID);

###
#
# AWS IAM Role Table
#
###

CREATE TABLE AWS_IAM_ROLE(
  ID CHAR(36) NOT NULL,
  AWS_ACCOUNT_ID VARCHAR(255) NOT NULL,
  AWS_IAM_ROLE_NAME VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE AWS_IAM_ROLE
  ADD UNIQUE INDEX `IX_AWS_IAM_ROLE_ACCT_ID_ROLE_NAME` (AWS_ACCOUNT_ID, AWS_IAM_ROLE_NAME);

###
#
# AWS IAM Role Permissions Join Table
#
###

CREATE TABLE AWS_IAM_ROLE_PERMISSIONS(
  ID CHAR(36) NOT NULL,
  AWS_IAM_ROLE_ID CHAR(36) NOT NULL,
  ROLE_ID CHAR(36) NOT NULL,
  SDBOX_ID CHAR(36) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE AWS_IAM_ROLE_PERMISSIONS
  ADD UNIQUE INDEX `IX_AWS_IAM_ROLE_TO_SDBOX` (AWS_IAM_ROLE_ID, SDBOX_ID);

ALTER TABLE AWS_IAM_ROLE_PERMISSIONS
  ADD FOREIGN KEY (AWS_IAM_ROLE_ID) REFERENCES AWS_IAM_ROLE(ID);

ALTER TABLE AWS_IAM_ROLE_PERMISSIONS
  ADD FOREIGN KEY (SDBOX_ID) REFERENCES SAFE_DEPOSIT_BOX(ID);

ALTER TABLE AWS_IAM_ROLE_PERMISSIONS
  ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID);

###
#
# Create the default categories.
#
###

INSERT INTO CATEGORY(ID, DISPLAY_NAME, PATH, CREATED_BY, LAST_UPDATED_BY, CREATED_TS, LAST_UPDATED_TS)
  VALUES(UUID(), 'Applications', 'app', 'system', 'system', utc_timestamp, utc_timestamp);
INSERT INTO CATEGORY(ID, DISPLAY_NAME, PATH, CREATED_BY, LAST_UPDATED_BY, CREATED_TS, LAST_UPDATED_TS)
  VALUES(UUID(), 'Shared', 'shared', 'system', 'system', utc_timestamp, utc_timestamp);

###
#
# Create the only roles.
#
###
INSERT INTO ROLE(ID, NAME, CREATED_BY, LAST_UPDATED_BY, CREATED_TS, LAST_UPDATED_TS)
  VALUES (UUID(), 'owner', 'system', 'system', utc_timestamp, utc_timestamp);
INSERT INTO ROLE(ID, NAME, CREATED_BY, LAST_UPDATED_BY, CREATED_TS, LAST_UPDATED_TS)
  VALUES (UUID(), 'write', 'system', 'system', utc_timestamp, utc_timestamp);
INSERT INTO ROLE(ID, NAME, CREATED_BY, LAST_UPDATED_BY, CREATED_TS, LAST_UPDATED_TS)
  VALUES (UUID(), 'read', 'system', 'system', utc_timestamp, utc_timestamp);
