###
#
# IAM Role KMS Keys Table
#
###

CREATE TABLE AWS_IAM_ROLE_KMS_KEY(
  ID CHAR(36) NOT NULL,
  AWS_IAM_ROLE_ID CHAR(36) NOT NULL,
  AWS_REGION VARCHAR(32) NOT NULL,
  AWS_KMS_KEY_ID VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  LAST_UPDATED_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE AWS_IAM_ROLE_KMS_KEY
  ADD UNIQUE INDEX `IX_IAM_ROLE_TO_REGION` (AWS_IAM_ROLE_ID, AWS_REGION);

ALTER TABLE AWS_IAM_ROLE_KMS_KEY
  ADD FOREIGN KEY (AWS_IAM_ROLE_ID) REFERENCES AWS_IAM_ROLE(ID);
