ALTER TABLE SECURE_DATA
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;

ALTER TABLE SECURE_DATA_VERSION
  CHANGE ACTION_TS ACTION_TS DATETIME(3) NOT NULL,
  CHANGE VERSION_CREATED_TS VERSION_CREATED_TS DATETIME(3) NOT NULL;

ALTER TABLE SAFE_DEPOSIT_BOX
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;

ALTER TABLE USER_GROUP_PERMISSIONS
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;

ALTER TABLE USER_GROUP
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;

ALTER TABLE AWS_IAM_ROLE_PERMISSIONS
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;

ALTER TABLE AWS_IAM_ROLE
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;

ALTER TABLE CATEGORY
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;

ALTER TABLE ROLE
  CHANGE CREATED_TS CREATED_TS DATETIME(3) NOT NULL,
  CHANGE LAST_UPDATED_TS LAST_UPDATED_TS DATETIME(3) NOT NULL;