ALTER TABLE SECURE_DATA
  ADD COLUMN LAST_ROTATED_TS DATETIME NOT NULL DEFAULT '1970-01-01';

ALTER TABLE SECURE_DATA_VERSION
  ADD COLUMN LAST_ROTATED_TS DATETIME NOT NULL DEFAULT '1970-01-01';

ALTER TABLE SECURE_DATA
  ADD INDEX `IX_SECURE_DATA_LAST_ROTATED_TS` (LAST_ROTATED_TS);

ALTER TABLE SECURE_DATA
  ADD INDEX `IX_SECURE_DATA_LAST_UPDATED_TS` (LAST_UPDATED_TS);

ALTER TABLE SECURE_DATA_VERSION
  ADD INDEX `IX_SECURE_DATA_VERSION_LAST_ROTATED_TS` (LAST_ROTATED_TS);

ALTER TABLE SECURE_DATA_VERSION
  ADD INDEX `IX_SECURE_DATA_VERSION_VERSION_CREATED_TS` (VERSION_CREATED_TS);