ALTER TABLE SAFE_DEPOSIT_BOX
ADD COLUMN SDB_NAME_SLUG varchar(255) NOT NULL;

UPDATE SAFE_DEPOSIT_BOX
JOIN (
  select substr(PATH_TRAILING_PATH_REMOVED, LOCATE('/', PATH_TRAILING_PATH_REMOVED) + 1, LENGTH(PATH_TRAILING_PATH_REMOVED)) as SDB_NAME_SLUG, SDB_ID
  from (
    select SUBSTR(PATH, 1, LENGTH(PATH) -1) as PATH_TRAILING_PATH_REMOVED, ID as SDB_ID
    from SAFE_DEPOSIT_BOX
  ) as PATH_TRAILING_PATH_REMOVED_VIRTUAL_TABLE
) as JOINED_VIRTUAL_TABLE on SDB_ID = SAFE_DEPOSIT_BOX.ID
SET SAFE_DEPOSIT_BOX.SDB_NAME_SLUG=(JOINED_VIRTUAL_TABLE.SDB_NAME_SLUG)
WHERE JOINED_VIRTUAL_TABLE.SDB_ID = SAFE_DEPOSIT_BOX.ID;