###
#
# Create Table for JWT Blacklist
#
###

CREATE TABLE JWT_BLACKLIST(
  ID CHAR(36) NOT NULL,
  EXPIRES_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE JWT_BLACKLIST
  ADD INDEX `IX_JWT_BLACKLIST_EXPIRES_TS` (EXPIRES_TS);