###
#
# Create Table for JWT Blocklist
#
###

CREATE TABLE JWT_BLOCKLIST(
  ID CHAR(36) NOT NULL,
  EXPIRES_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE JWT_BLOCKLIST
  ADD INDEX `IX_JWT_BLOCKLIST_EXPIRES_TS` (EXPIRES_TS);