###
#
# Create Table for Authentication Table
#
###

CREATE TABLE AUTH_TOKENS(
  ID CHAR(36) NOT NULL,
  TOKEN_HASH VARCHAR(255) NOT NULL,
  CREATED_TS DATETIME NOT NULL,
  EXPIRES_TS DATETIME NOT NULL,
  PRINCIPAL VARCHAR(255) NOT NULL,
  PRINCIPAL_TYPE VARCHAR(255) NOT NULL,
  IS_ADMIN BOOLEAN NOT NULL,
  GROUPS TEXT,
  REFRESH_COUNT INTEGER,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE AUTH_TOKENS
  ADD UNIQUE INDEX `IX_AUTH_TOKENS_TOKEN_HASH` (TOKEN_HASH);

CREATE TABLE SECURE_DATA(
  ID CHAR(36) NOT NULL,
  SDBOX_ID CHAR(36) NOT NULL,
  PATH VARCHAR(255),
  ENCRYPTED_BLOB BLOB,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE SECURE_DATA
  ADD FOREIGN KEY (SDBOX_ID) REFERENCES SAFE_DEPOSIT_BOX(ID);

ALTER TABLE SECURE_DATA
  ADD UNIQUE INDEX `IX_SECURE_DATA_PATH` (PATH);