ALTER TABLE SECURE_DATA
  ADD COLUMN `TYPE` VARCHAR(255) NOT NULL,
  ADD COLUMN SIZE_IN_BYTES INTEGER NOT NULL;

UPDATE SECURE_DATA
  SET `TYPE` = 'OBJECT',
      SIZE_IN_BYTES = -1;

ALTER TABLE SECURE_DATA
  ADD INDEX `IX_SECURE_DATA_TYPE` (`TYPE`);


ALTER TABLE SECURE_DATA_VERSION
  ADD COLUMN `TYPE` VARCHAR(255) NOT NULL,
  ADD COLUMN SIZE_IN_BYTES INTEGER NOT NULL;

UPDATE SECURE_DATA_VERSION
  SET `TYPE` = 'OBJECT',
      SIZE_IN_BYTES = -1;

ALTER TABLE SECURE_DATA_VERSION
  ADD INDEX `IX_SECURE_DATA_VERSION_TYPE` (`TYPE`);