###
#
# Create Table for Secrets Versioning
#
###

CREATE TABLE SECURE_DATA_VERSION(
  ID CHAR(36) NOT NULL,
  SDBOX_ID char(36) NOT NULL,
  PATH varchar(255) NOT NULL,
  ENCRYPTED_BLOB MEDIUMBLOB,
  ACTION varchar(100) NOT NULL,
  VERSION_CREATED_BY VARCHAR(255) NOT NULL,
  VERSION_CREATED_TS DATETIME NOT NULL,
  ACTION_PRINCIPAL VARCHAR(255) NOT NULL,
  ACTION_TS DATETIME NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE SECURE_DATA_VERSION
  ADD FOREIGN KEY (SDBOX_ID) REFERENCES SAFE_DEPOSIT_BOX(ID);

ALTER TABLE SECURE_DATA_VERSION
  ADD INDEX `IX_SECURE_DATA_VERSION_PATH` (PATH);


ALTER TABLE SECURE_DATA
  ADD COLUMN CREATED_BY VARCHAR(255) NOT NULL,
  ADD COLUMN CREATED_TS DATETIME NOT NULL,
  ADD COLUMN LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  ADD COLUMN LAST_UPDATED_TS DATETIME NOT NULL;

UPDATE SECURE_DATA
  SET CREATED_BY = 'SYSTEM',
    CREATED_TS = UTC_TIMESTAMP(),
    LAST_UPDATED_BY = 'SYSTEM',
    LAST_UPDATED_TS = UTC_TIMESTAMP();